// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enxdzmsvmaqcimccosgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVueGR6bXN2bWFxY2ltY2Nvc2djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4OTg2MjcsImV4cCI6MjA1NzQ3NDYyN30.-bv2QvcZh_7Ln7MA_7mwZ_7Lr5C7HdHQZYFjlEipd20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);